metricbeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    # Reload module configs as they change:
    reload.enabled: true
    reload.period: 10s

metricbeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true

metricbeat.modules:
  - module: nginx
    metricsets: ["stubstatus"]
    hosts: ["http://nginxstatus.fivepoints.fr"]
  - module: logstash
    hosts: ["logstash:5000"]
  - module: docker
    metricsets:
      - "container"
      - "cpu"
      - "diskio"
      - "healthcheck"
      - "info"
      - "memory"
      - "network"
    hosts: ["unix:///var/run/docker.sock"]
    period: 10s
    enabled: true
  - module: mongodb
    metricsets: ["dbstats", "status", "collstats", "metrics", "replstatus"]
    hosts: ["mongodb://127.0.0.1:27017"]
    period: 10s
    enabled: true

processors:
  - add_cloud_metadata: ~

output.elasticsearch:
  hosts: '${ELASTICSEARCH_HOSTS:elasticsearch:9200}'
  username: '${ELASTICSEARCH_USERNAME:}'
  password: '${ELASTICSEARCH_PASSWORD:}'